# -*- coding: utf-8 -*-
"""Program 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A2FbsXV79T7GlVLugR6E2-lSj0uwz8m6
"""

import numpy as np
array_list=np.array([1,2,3,4,5])
print("Array from list:",array_list)

array_range=np.arange(10)
print("Array with range:",array_range)

zeros_array=np.zeros((3,3))
print("Array of zeros:\n",zeros_array)

ones_array=np.ones((2,5))
print("Array of ones:\n",ones_array)

a=np.array([1,2,3])
b=np.array([4,5,6])

addre=np.add(a,b)
print("Addition:",addre)

a=np.array([1,2,3])
b=np.array([4,5,6])
addre=np.add(a,b)
print("Addition:",addre)
subre=np.subtract(a,b)
print("Subtraction:",subre)
mulre=np.multiply(a,b)
print("Multiplication:",mulre)
divre=np.divide(a,b)
print("Division:",divre)

array=np.arange(12)
print("Original array:",array)
reshaped_array=array.reshape((3,4))
print("Reshaped to 3x4:\n",reshaped_array)
reshaped_array3d=array.reshape((2,3,2))
print("Reshaped to 2x3x2:\n",reshaped_array3d)

array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array:\n",array_2d)
element=array_2d[1,2]
print("Element at (1,2):",element)

subarray=array_2d[1:3,0:2]
print("Sliced subarray :\n",subarray)

column=array_2d[:,1]
print("Column 1:",column)

array=np.array([1,2,3,4,5,6,7,8,9,10])
mean=np.mean(array)
print("Mean:",mean)
median=np.median(array)
print("Median:",median)
std_dev=np.std(array)
print("Standard deviation:",std_dev)
min_val=np.min(array)
max_val=np.max(array)
print("Minimum value:",min_val)
print("Maximum value:",max_val)