# -*- coding: utf-8 -*-
"""Program 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjMWY6_-iq5EoC0udemlKnYyoq68zMVi
"""

import numpy as np
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[9,8,7],[6,5,4],[3,2,1]])
matrix_sum=matrix1+matrix2
matrix_diff=matrix1-matrix2
matrix_product=matrix1*matrix2
matrix_div=matrix1/matrix2
matrix_multiply=np.dot(matrix1,matrix2)
matrix1_transpose=np.transpose(matrix1)
diagonal_sum=np.trace(matrix1)
print("Matrix 1:\n",matrix1)
print("Matrix 2:\n",matrix2)
print("Matrix sum:\n",matrix_sum)
print("Matrix difference:\n",matrix_diff)
print("Matrix element wise product:\n",matrix_product)
print("Matrix element wise division:\n",matrix_div)
print("Matrix multiplication:\n",matrix_multiply)
print("Transpose of Matrix 1 :\n",matrix1_transpose)
print("Sum of disagonal elements of matrix 1:\n",diagonal_sum)

subarray=array_2d[1:3,0:2]
print("Sliced subarray:\n",subarray)