# -*- coding: utf-8 -*-
"""program3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjiLHNi880iBkHdNgTcWYRMMxXWzc-Fl
"""

import numpy as np;
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print("Matrix X is:\n",x)
print("Matrix Y is:\n",y)
a=np.power(x,2)
print("X^2=",a)
result=a+2*y
print("X^2+2*Y IS \n",result)