# -*- coding: utf-8 -*-
"""program4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Or8U-cxuDd-mGql3H2ksbjnFwhCwjzU_
"""

import numpy as np
twodarr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
excluding_first_row=twodarr[1:]
excluding_last_column=twodarr[:,:-1]
column12inrow23=twodarr[1:3,0:2]
column23=twodarr[:,1:3]
elements23infirstrow=twodarr[0,1:3]
descorder=twodarr.ravel()[::-1][4:11]
print("Original 2D array:\n",twodarr)
print("Elements excluding the first row:\n",excluding_first_row)
print("Elements excluding the last column:\n",excluding_last_column)
print("Elements of the 1st and 2nd column in the 2nd and 3rd row:\n",column12inrow23)
print("Elements of the 2nd and 3rd column :\n",column23)
print("2nd and 3rd element of the first row :\n",elements23infirstrow)
print("Elements from indices 4 to 10 in descending order:\n",descorder)