# -*- coding: utf-8 -*-
"""Program_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNDhWgCtlXovON53R1ZevIqG91LWvkKG
"""

import numpy as np
a=np.array([[2,1,-2],[3,0,1],[1,1,-1]])
b=np.array([-3,5,-2])
x=np.linalg.solve(a,b)
print("Matrix A:")
print(a)
print("Vector b:")
print(b)
print("Solution for X:")
print(x)